Fix logic error in configfile test

diff --git a/tools/arkmanager b/tools/arkmanager
--- a/tools/arkmanager
+++ b/tools/arkmanager
@@ -1647,7 +1647,11 @@ useConfig() {
     fi
   done
   if [ -z "$configfile" ]; then
-    echo "Error: config file ${configfile} does not exist"
+    echo "Error: no config files for instance $1"
+    exit 1
+  fi
+  if [ ! -f "$configfile" ]; then
+    echo "Error: config file $configfile does not exist"
     exit 1
   fi
   source "$configfile"
